Caraxi/SimpleTweaksPlugin

- Tweaks/UiAdjustment/NotificationToastAdjustments.cs
Hey, small tweak for something I find annoying. First time doing anything UI related, so don't hesitate to tell me if something is weird/bad (or if you're not interested ^^).
Toast:
Settings:
Default, always show with some exceptions if desired + the ability of changing its position.
Always hidden except in combat.
Always hidden.
> Add Tweak: Notification Toast Adjustments

- Tweaks/UiAdjustment/NotificationToastAdjustments.cs
Only happening when exiting the game, so it's just to avoid an exception in logs 😃.
> Fix null ref exception in Notification Toast tweak

- Tweaks/UiAdjustment/ShowShieldOnHPBar.cs
This tweaks shows a bar on the HP parameter bar which represents the approx. value of the
current shield.
Two NineGridNods are used, one for shield values over max HP and another for under.
> feat: UiTweak `ShowShieldOnHPBar`

- Tweaks/UiAdjustment/HideAchievementsNotifications.cs
Since the game says "either you get a window or a login notification, but you can't choose neither".
> Add tweak to hide achievements nearing completion

- Tweaks/UiAdjustment/HideExperienceBar.cs
In 6.0 until 6.1, it'll be wrong for BLU, but as discussed in #plugin-dev, it's either hardcode it and update it or do it this way. I chose this way. You can hardcode it if you want, though.
> Add a tweak to hide the xp bar at max level

- Tweaks/UiAdjustment/RemoveQuestMarkerLimit.cs
What it says on the tin. This removes the 5-quest-limit in the area map and minimap. Doesn't seem to effect the zoomed-out all-zones map view, but I'm already at the end of my rope with getting this working.
Won't take effect until some quest-related event (accepting, completing, or toggling in the journal) occurs. Again, tried to make it automatic but failed dismally.
No credit because it'd list like 4.5 people.
> Add `Remove Quest Marker Limit` tweak

- Tweaks/UiAdjustment/HideJobGauge.cs
Inspired by an option in the delvui plugin, and thanks to the help of Eternita, I added the option to show the Job Gauge if the player character has their weapon drawn.
> [`HideJobGauge`]  : Option to show gauge while character weapon is drawn

- Tweaks/UiAdjustment/ExtendedDesynthesisWindow.cs
Instead of showing your desynthesis skill, it'll show the difference between your skill and the item's desynthesis level, much like the option for the "Show Desynthesis Skill" tooltip tweak.
This is helpful for determining at a glance which items above your skill level to desynthesize first.
> Option to show delta in extended desynthesis window

- Tweaks/SmartStrafe.cs
A new tweek that automatically switches keyboard controls between turning and strafing based on combat status, and optionally disables diagonal backpedaling.
> New Tweak: `Smart Strafe`

- Tweaks/RememberQuickGathering.cs
A tweak that remembers the last state of quick gathering and re-applies it when opening a new node (if available,) even after it was reset by gathering at an unspoiled node.
> Add Tweak: Remember Quick Gathering

- Tweaks/UiAdjustment/LargeCooldownCounter.cs
Adjusts the Update() function to account for when Expanded Hold Controls are being used, and reference the correct target bar and slots.
> Fix for Issue #260 re: Large Cooldown Timers

- Tweaks/UiAdjustment/ChangeMapAreaColors.cs
This tweak allows users to set their own colors for the area indicator on maps (e.g. quest, leve, and FATE region circles).
> New Tweak: Change Map Area Colors

- Tweaks/Tooltips/TrackFadedRolls.cs
This tweak adds the yellow Collected checkmark and "Obtained/Registered" mark to faded orchestrion rolls.
If a faded orchestrion roll can be used to craft multiple rolls, the Collected mark will only show if all crafted roles are unlocked.
> New Tweak: Track Faded Orchestrion Rolls

- Tweaks/RefreshMarketPrices.cs
- Utility/Common.cs
* if the "Please wait and try your search again." message is shown when trying to see an item's prices, refresh the list half a second later. If the same message is shown again it will keep refreshing until the prices are fetched (typically happens once or twice).
* replaces the "Please wait and try your search again." message with "Please wait..." so people know they don't need to manually refresh it
> Refresh Market Prices

- Tweaks/SanctuarySprintReplacer.cs
This tweak aims to redirect uses of the "Sprint" action to "Isle Sprint" while in the Island Sanctuary. Note that at this time it does not edit the hotbar or copy cooldown information.
Testing notes: this tweak *should* probably be safe, probably. I don't have the ability to test if it works while on the Sanctuary but before unlocking Isle Sprint, but I suspect it should be fine.
> New Tweak: Island Sanctuary Sprint Replacer

- Tweaks/SanctuarySprintReplacer.cs
- Tweaks/UiAdjustment/ChangeMapAreaColors.cs
This was supposed to stay simple, then Goat suggested I use attributes.
- Add all the map circle colors this game has
- Add hint text to explain what some of the circle colors do
- Add default colors that mostly match in-game
- Fix some language to better reflect what Rave Mode does
- Add Reset Button because I'm sure it'll be useful to someone
I'm also sneaking in removing experimental mode from the Island Sanctuary Sprint Replacer tweak here, as I suspect the release timing will work out favorably. Let me know if you want that in a separate PR.
> [`Change Map Area Colors`] Partial Rewrite for 6.2

- Tweaks/UiAdjustment/ActionPressMirroring.cs
Added a new tweak to duplicate the action press pulse that happens when you press an ability onto any other hotbar slot with the same ability. Currently only works for pulse from regular hotbars and does not mirror the pulse when you click or the pulse from cross hotbar. It does however mirror pulses from regular hotbars onto the cross, expanded cross, and double cross hotbars.
This functionality has been requested multiple times by people that use the `Control Hint Mirroring`. I've put it into a separate tweak however so people can use it without `Control Hint Mirroring` if they'd like.
> New Tweak: `Action Press Mirroring`

- Tweaks/Tooltips/DesynthesisSkill.cs
- strings.json
Similar to daemitus's comment in #50, I like to GC turnin things that isn't going to offer me any skill ups, but rather than desynth first, I'd like to turn in first to clean up inventory, and continue collecting, to build up a bunch to desynth at the same time (and thus optimize use of potions/food).  This commit adds the same coloring idea found in the ExtendedDesynthesisWindow to the Item Hover tooltip making it easy to see in the GC turnin (as well as anywhere I hover).
> Optionally color the Tooltip Desynthesis delta/level similar to the ExtendedDesynthesisWindow

- Tweaks/Chat/HideChat.cs
- Tweaks/Chat/HideChatAuto.cs
This tweak has been separated from this one - https://github.com/Caraxi/SimpleTweaksPlugin/pull/412
This provides automatic chat hiding based on configurable conditions.
> New Tweak: Hide Chat Automatically

- Tweaks/Chat/StickyChat.cs
Persistently sets chat channel when sending messages such as:
`/p hey yall`
This will set the actual chat channel to party,
This is extremely useful for folks that have come from other MMO's where sending a message in a channel, sets that as the active channel.
> Add Sticky Chat

- Tweaks/HighResScreenshots.cs
This hooks the function polled for screenshot inputs and adjusts the resolution of the game when pressed. It does not resize the game window.
HUD elements and ImGui windows are not resized, so they look janky while doing this.
Not sure if I should make experimental or not.
> Add High Resolution Screenshots

- Tweaks/UiAdjustment/LootWindowDuplicateUniqueItemIndicator.cs
The name could definitely be improved.
This might not be the best approach for indicating to the user that they already have a unique item, but it is functional.
> Add Loot Window Enhancement Tweak

- Tweaks/UiAdjustment/ImprovedInterruptableCastbars.cs
Adds skill icons to interruptable cast bars
Icon changes based on your role and level.
Works with either HUD setting for combined castbar, or separated castbar
> Add Improved Interruptable Castbars Tweak

- Tweaks/UiAdjustment/LootWindowDuplicateUniqueItemIndicator.cs
While cleaning up unused variables in the last fix, managed to accidentally delete the set position lines.
> `Enhanced Loot Window` Fix Node Position

- Tweaks/UiAdjustment/ImprovedInterruptableCastbars.cs
- Utility/UiHelper.Nodes.cs
Fixes exception in log that occurs on login when the addons are being constructed internally.
Initially I was going to add additional exception checking in LinkNodeAtEnd, but realized its better for the consumer to check that the addon is valid before attempting to allocate the node.
> `Improved Interruptable Castbars` Fixes

- Tweaks/UiAdjustment/ImprovedDutyFinderSettings.cs
This requires a CS update to fix the LootRules offset ([this commit](https://github.com/aers/FFXIVClientStructs/commit/d31a084f59027fe876b4cf1f994c2dcf379ca5fa)).
I do want to try using native nodes, but this is a good in-between for now imo.
https://streamable.com/kpppo2
> New Tweak: [`Improved Duty Finder Settings`]

- Tweaks/UiAdjustment/HideUnwantedBanner.cs
Use void return instead of nint
Simplify Logic.
The hooked function is only called by AddonImage.vf71 and AddonImage.vf72, and neither of them capture a return value.
> Cautionary Fix for `Hide Unwanted Banner`

- Tweaks/KeyInterrupt.cs
This PR aims to add the `Keyboard Gaming Mode` tweak, a new feature that will allow users to block certain undesirable keystrokes while in-game. Users will be able to selectively disable `Alt-Tab`, the `Windows` (`Meta`) key, and `Ctrl-Esc` while still retaining the ability to use them as keybinds.
I'm marking this tweak as Experimental as I'm not particularly sure how much load this will add to the system, nor how much it will break for certain users and use cases. I've been testing it for a while and have had no issues, but I'm just a single data point.
> Add `Keyboard Gaming Mode` Tweak

- Tweaks/UiAdjustment/ExpandedCurrencyDisplay.cs
Use SimpleTweaks culture for number formatting...
**Maybe** fixes French number display. (Unverified)
> `Expanded Currency Display` Fix Culture

- Tweaks/UiAdjustment/FadeUnavailableActions.cs
Basically KitchenSync, but **actually** simple.
Instead of darkening actions, they will be made transparent instead.
Transparency % is configurable, function is only called when a refresh is requested so this should be significantly more efficient than what KitchenSync does.
> Add `Fade Unavailable Actions` Tweak

- Tweaks/UiAdjustment/FadeUnavailableActions.cs
Removed Multiply RGB override
Only apply effect to combat actions, otherwise clear it
> `Fade Unavailable Actions` 

- Tweaks/Chat/EchoStorySelection.cs
Also, adds option to display characters name instead of "Story Selection"
This tweak triggers on CutSceneSelectString, and on SelectString.
SelectString will print to chat when InQuestEvent, which will be pretty much every SelectString.
> `Echo Story Selection` Fix Bounds Exception

- Tweaks/UiAdjustment/ResizeExperienceBar.cs
Lets the user change the horizontal scale of the experience bar components without touching the text components, it also contains an option to align the sanctuary and pvp icons to the left of the base component.
> New Tweak `Change Size Experience Bar`

- Tweaks/UiAdjustment/LootWindowDuplicateUniqueItemIndicator.cs
I haven't tested if this actually fixes this issue, but I believe it to be pretty obviously the reason why it happened.
When the image nodes are created I default them both to visible, and then set them in the OnRequestedUpdate hook.
> [`Enhanced Loot Window`] Fix HQ Items

- Tweaks/UiAdjustment/ColoredDutyRoulette.cs
Adds the ability to select individual roulettes for recoloring
> `Color Duty Roulette Names` Add Additional Options

- Tweaks/UiAdjustment/DutyListBackground.cs
Should make the "aesthetician crash" entirely impossible to happen.
> [`DutyListBackground`] Auto Disable Near Bell

- Tweaks/UiAdjustment/ImprovedInterruptableCastbars.cs
Only the IsAddonReady in TryFreeImageNode was needed, but it doesn't hurt to have everywhere =D
This'll make sure the addon, the root node, and the first child are all valid before trying anything.
> [`ImprovedInterruptableCastbars`] Fix NRE on Dispose

- Tweaks/Tooltips/MateriaStats.cs
The below image shows CP being capped to +10, when the game and other melding sites show +11 as the cap.
[.NET rounds floats and doubles towards even integers](https://stackoverflow.com/a/977807), causing discrepancies where values like 10.5 should've been rounded up towards 11.
> [`Materia Stats`] Fix materia cap rounding error

- Tweaks/UiAdjustment/HideQualityWhenNoHQ.cs
The quality bar should be shown for expert recipes, even though the recipes aren't considered "CanHQ".
> [`HideQualityWhenNoHQ`] Fix for expert recipes

- tweakBlacklist.txt
Dalamud updated its ClientStructs, so now they have a span that is size 16 and the live version of this tweak is indexing to size 32.
This PR is an alternative to releasing a SimpleTweaks update.
> [`EnhancedLootWindow`] Ban Enhanced Loot Window

- Tweaks/UiAdjustment/LootWindowDuplicateUniqueItemIndicator.cs
Use SpanHelper `WithIndex` instead.
This should work happily with any version of ClientStructs.
> [`EnhancedLootWindow`] Remove Hardcoded Range

- Tweaks/UiAdjustment/LootWindowSelectNext.cs
Depends on unmerged clientstructs PR: https://github.com/aers/FFXIVClientStructs/pull/528
Alternatively I could include a copy of these structs in the tweak.
This tweak will automatically select the next item in the loot list after clicking "need" "greed" or "pass"
No decisions are being made on behalf of the user, and no data is being sent to the servers.
This tweak does not pass-all, greed-all, or need-all, it only advances the selected item one spot each time "need" "greed" or "pass" is pressed.
There seems to be some kind of built in rate-limit already in the vanilla button events that prevents a user from rolling on items unreasonably quickly. (See attached clip to see what happens when you spam click)
https://github.com/Caraxi/SimpleTweaksPlugin/assets/9083275/8ad65d44-aac5-4568-ac67 …
> [`LootWindowSelectNext`] Add New Tweak

- SimpleTweaksPlugin.cs
Fixes error spam on framework when SimpleTweaks.Plugin.Error is called without a tweak parameter.
> `Debug` Fix error spam

- Tweaks/Chat/StickyChat.cs
- Tweaks/ChrDirCommand.cs
- Tweaks/SmartStrafe.cs
- Tweaks/Tooltips/TrackFadedRolls.cs
- Tweaks/UiAdjustment/ActionPressMirroring.cs
- Tweaks/UiAdjustment/AlwaysYes.cs
- Tweaks/UiAdjustment/ReducedDeepDungeonInfo.cs
This changes the Chat, ChrDirCommand, SmartStrafe, Tooltips, ActionPressMirroring, AlwaysYes, FadeUnavailableActions, and ReducedDeepDungeonInfo tweak descriptions to fix various errors.
These edits are so small I piled it into one big PR, let me know if I should separate them instead.
> Various typo and grammar fixes for tweak descriptions

- Tweaks/UiAdjustment/LootWindowDuplicateUniqueItemIndicator.cs
Let me start off by saying I'm not familiar with native UI at all so many assumptions I've made here could be totally wrong.
When working on a loot window modification using this tweak as a base, I noticed that `UiHelper.UnlinkAndFreeImageNode` wasn't being called (successfully or at all). This was due to two issues:
1. The first issue was that `crossNode` and `padlockNode` could not be found during addon finalize. I fixed this by looking for them in `lootItemNode`'s `UldManager` instead of the list component's `UldManager`. This is what `UpdateNodeVisibility` does and it seems to be correct.
2. After fixing the above, the second issue was that `AddonNeedGreed` (which is passed to `UiHelper.UnlinkAndFreeImageNode`) was returning a null pointer during finalize. I guess at this stage of …
> [`EnhancedLootWindow`] Fix freeing of image nodes during finalize

- Tweaks/UiAdjustment/ShowShieldOnHPBar.cs
It was previously thought that `AddRed` etc. were `ushort`, but they are actually `short`. This code used to work by coincidence because `ushort.MaxValue` is -1 when read as a `short`, but now it results in a pure white bar. Probably they should just be zero.
> [`ShowShieldOnHPBar`] Fix bar color

- Tweaks/UiAdjustment/LootWindowSelectNext.cs
Removed the null check from AddonSetup, because AddonLifecycle literally can't be called from a null addon pointer.
> [`LootWindowSelectNext`] Modernize Tweak

- Debugging/UIDebug.cs
Fixes the parts display when using `_hr1` textures
> [`UIDebug`] Fix Parts Display

- Debugging/EventsDebugging.cs
- Events/AddonEventAttribute.cs
- Events/EventController.cs
- Events/TerritoryChangedAttribute.cs
- Tweaks/AutoLockHotbar.cs
- Tweaks/Chat/EchoPartyFinder.cs
- Tweaks/Chat/HideChatPanelButtons.cs
- Tweaks/UiAdjustment/MinimapAdjustments.cs
- Tweaks/UiAdjustment/ParameterBarAdjustments.cs
Added `AddonPreReceiveEvent`, `AddonPostReceiveEvent` attributes
Added `TerritoryChangedAttribute`
Added TerritoryChanged to Event Debugger
Modified Event Debugger to show header text for Framework and TerritoryChanged
I had to add another static constructor for EventSubscriber because Kind is private set
Changed Invoke to `object` to support other parameter values such as territory id
Fixed TerritoryChange delegate leak from MiniMapAdjustments
> [`EventController`] Additional Events

- Tweaks/UiAdjustment/ImprovedCraftingLog.cs
Restart the timer when changing jobs to allow the framework update event to unsubscribe.
Also reordered the method to force update after checking states rather than before.
> [`ImprovedCraftingLog`] Fix Framework Update event handler unsubscribing

- Tweaks/UiAdjustment/TargetCastbarCountdown.cs
For casts with really long cast times, the timer would only updated when the bar moved, this causes it to only update every other second or so in some cases.
> [`TargetCastbarCountdown`] Fix Update Rate

- Tweaks/UiAdjustment/ColoredDutyRoulette.cs
This tweak was updated to use `DrawConfig`, but its `Setup` method doesn't call `base.Setup()`, so `AttemptDrawConfigSetup()` is never called. As a result, the config UI doesn't draw. I just changed `Setup` to call the base method, which fixes this issue.
> [`ColorDutyRouletteNames`] Fix config UI not being displayed

- Tweaks/UiAdjustment/FastSearch.cs
(What it says on the tin)
Feedback from @\ackwell
> ref. fast/fuzzy item search - i've not checked if you've got a ranking algo or not, but if you don't (or, if you do, and two items are the same score), can i suggest secondary sort of item ID? at the moment the results are non-deterministic which makes it annoying to find something across the same search plural times
> [`FastSearch`] Fix ordering of results

- Tweaks/UiAdjustment/FadeUnavailableActions.cs
Avoid checking/calculating the slot index, as it causes issues with "pet swap" mode on Hotbar 1 and also avoids needing to calculate the slot number for certain extended hotbars (e.g. on XHB/WXHB) which doesn't work correctly right now. Then, instead of using `RaptureHotbarModule` to get the action type, define the enum representing number array action types (`NumberArrayActionType`) and check that instead. This makes pet swap and cross hotbar buttons work as expected.
> [`Fade Unavailable Actions`] Fix pet swap and cross action bar issues

- Tweaks/UiAdjustment/CastingTextVisibility.cs
Allows the user to change target + focus target casting text colour and font size. (I have bad eyesight)
would have liked to add a thicker edge or background but I couldn't get it to work :(
I based it off of TargetHp, so sorry if something's off.
> [Casting Text Visibility] add new tweak

- Tweaks/UiAdjustment/ColoredDutyRoulette.cs
Figured out how to use the AtkComponentTreeList structure to iterate over the nodes in a more sensible manner.
The rendering bug the causes other tabs to get colored is due to an incorrect offset in [AgentContentsFinder](https://github.com/aers/FFXIVClientStructs/pull/692).
> [`ColoredDutyRoulette`] Code Simplification

- Tweaks/Tooltips/GlamItemNames.cs
- Utility/CustomNodes.cs
A tweak to show both the item's name and the glamour name at the same time in tooltips, instead of fading between the two. It's a tweak I've been wanting for a while.
The game has roughly enough space for 2 lines of text in the tooltips, which it does use. Going up to 3 lines was inconsistent in how the text looked, so I aim to get to two. For most items, it looks absolutely fine, though for very long names it's a *little* annoying? I've been thinking about how I could make it better without having to mess with the entire tooltip (and likely break other tweaks and plugins), but it's so narrow I don't think it'll matter much.
The node creation code is heavily based off of the AdditionalItemInfo tweak.
This is my first real time writing C# (though I have experience with other languages), …
> [`GlamItemNames`] New Tweak

- Service.cs
- SimpleTweaksPlugin.cs
- Tweaks/EmoteLogServerBarEntry.cs
Added a new Tweak that tracks the status of the Emote Log in the server bar. This will respond to changes via either the Emotes UI panel, or the slash command /emotelog. Clicking on the entry in the bar will also toggle it.
Emote log off:
Emote log on:
> [`EmoteLogServerBarEntry`] New Tweak

- Tweaks/CutsceneCommands.cs
This is more to gauge interest for a random thing I hacked together that does kinda, sorta, maybe serve a similar purpose as SoundSetter. No issue if it's deemed unnecessary.
Also while the name implies it's cutscene bound, I didn't explicitly add a check because I couldn't think of a situation where you have access to chat, but wouldn't actually be able to set the game settings, so it works just fine if you're switching zones.
> [`CutsceneCommands`]  New Tweak

- Tweaks/SetOptionCommand.cs
A recent update added a couple of new values for this setting.
> [`Set Option Command`] Add "small" and "smallest" to `DisplayNameSize`

- Tweaks/SetOptionCommand.cs
Allows changing the title display for self, party members, alliance members, other players, and friends. I tried to use a similar pattern for the command names and aliases as `SelfNameTitle` etc, but I'm happy to use some other format if you'd prefer that.
> [`Set Option Command`] Add `*NameTitle` commands for changing `NamePlateNameTitleType*`

- Tweaks/Tooltips/FoodStats.cs
This pull request aims to fix a possible crash caused by the `FoodStats` tweak. The tweak was using `stringArrayData->SetValue(int, byte[], bool)` which ultimately resolved to `SetValueForced(int, byte*, bool)` via implicit conversion of `byte[]`. Per [a prior discussion](https://canary.discord.com/channels/581875019861328007/929533532185956352/1175485246565781605) this might cause an issue if things are GC'd, so it has been updated to use the newer/safer `SetTooltipString`.
It appears as though this specific call was just missed in commit 2826f17e and subsequently was never updated to use the `managed` variant in b5ec996b.
I've also verified that no other places in the code use the older `->SetValue` format via search, so this should be the last of these specific crashes. I'm not …
> [`FoodStats`] Use `SetTooltipString` for potions

- Tweaks/Tooltips/HideTooltipsInCombat.cs
Hiding crossbar hints out of combat wasn't working because it was duplicated and set to HidePopUpOoc instead.
Changing the duplicate Config.HidePopUpOoc to Config.HideCrossbarHintsOoc fixes this
> HideCrossbarhints Was Not Working in HideTooltipsInCombat.cs

- Tweaks/Chat/StickyShoutChat.cs
This pull request aims to add a new Tweak to make shout chat (and similar resetting channels) sticky.
The game appears to track temporary chat channels in `RaptureShellModule+10B4`, set in `ffxiv_dx11.exe+787E10`. This is then reset in `ffxiv_dx11.exe+787F00` if the return chat channel is not `-2`.
I opted to simply wipe out `787F00`, but I suppose the "return" channel can be set to -2 instead. This feels safer than intercepting and changing the behavior of `787E10` as a number of other things seem to get set in that method (although these are all reverted in `787F00`).
This design *might* have some stray side effects, but seems to perform reasonably in testing. Disabling the tweak while in `/shout` chat dumps you back to wherever you're supposed to be. As this design further only deals …
> [`StickyShoutChat`] Add New Tweak

- Tweaks/EquipJobCommand.cs
- strings.json
Adds a command to switch to a gearset given a job's abbreviation.
Inspired by the desire to have gearset index -independent macros.
Implementation details:
- The job's abbreviation is not case-sensitive.
- The highest item level gearset is selected
- Job abbreviations are pulled from excel
Will gladly accept suggestions, fixes, etc. It's been a _long_ time since I've used C#.
> [`EquipJobCommand`] New Tweak

- Utility/Common.cs
It seems like it triggers some OutOfMemoryExceptions for some people. I'm not exactly sure if that's what's happening, but making it simpler can't hurt I guess.
> Fix potential ReadSeString issue

- Tweaks/SetOptionCommand.cs
Toggles the automatic skipping of transport, scenario, and housing cutscenes.
> [`Set Option Command`] Add Skip*Cutscenes commands

- Tweaks/UseCollectionCommand.cs
Adds a `/usecollection` command to allow the use of Collection items (Aether Compass, Mogpendium, etc.) from commands.
The base game supports this parameterized style for e.g. /fashion but for for some reason doesn't for /collection, so this provides a way to do it. I was mainly motivated to add this so I can access collection items directly from Wotsit macro links.
I also made the command print unlocked Collection names/IDs to chat when no name or ID parameter is supplied, as the IDs are not visible anywhere otherwise.
Please let me know if there's anything you'd like changed.
> [`UseCollectionCommand`] New Tweak

- Tweaks/UiAdjustment/LimitTargetStatusEffects.cs
Fix focus target breaking + spamming exceptions when a non-battlechara is set.
> [`Target Status Adjustments`] Fix focus target on non-battlechara

- Tweaks/UseCollectionCommand.cs
The Field Record and Yo-kai Medallium records are swapped in `McGuffin` vs `McGuffinUIData` so I fixed the tweak logic to use the former for all logical checks and just look up UI info with the latter.
> [`Use Collection Command`] Fix swapped collection IDs

- Tweaks/UiAdjustment/AddNumberSeparators.cs
This PR ports the code from The Great Separator into a tweak. If unfamiliar, that plugin adds separators to various numbers (like damage numbers). `1000` becomes `1,000` for US English, for example.
I've tested it and it works as expected. I wasn't sure how to get it to appear in the UI tab, even though I had it inherit `UiAdjustments.SubTweak`.
Let me know if you need anything else or if you don't want to accept this. Thank you c:
> Convert The Great Separator into a tweak

- Tweaks/Chat/ChatNameColours.cs
There was a stray space in the Tweak description or Chat Name Colours. Was showing `th e` rather than `the`.
> Fix stray space in chat name colours tweak

- Debugging/UIDebug.cs
Currently the debug view only shows the uv coordinates for the texture loaded in the root part, it doesn't check each individual part.
The vanilla game doesn't seem to use different textures within a parts list, but KamiToolKit does, I allocate several textures in parts for ease of switching.
> Actually show AtkUldPart

- Tweaks/UiAdjustment/ColoredDutyRoulette.cs
No logic changes.
DailyDuty now also has this functionality but it depends on including roulettes in the todo / notification / tracking. Since I'd like this to apply to all roulettes, but only have certain roulettes in my DailyDuty todo list, this tweak is still useful.
> Update Color Duty Roulette Names

- SimpleTweaksPlugin.csproj
- Tweaks/UiAdjustment/FadeUnavailableActions.cs
Square added at least one new action type that threw off the enum, and added one more int value to the NumberArrayStruct, shifting IsTargetable down one entry.
The sig broke as well, but only very slightly.
> Update Fade Unavailable Actions

- Tweaks/TryOnCorrectItem.cs
Fixes the icon to match the displayed appearance when showing the "original" item.
> [`TryOnCorrectItem`] Fix incorrect icon

- Tweaks/TryOnCorrectItem.cs
My last fix wasn't quite enough. I think it should behave as before now after testing a bunch more scenarios. Sorry!
> [`TryOnCorrectItem`] Fix for unglamoured items

- SimpleTweaksPlugin.csproj
- Tweaks/DisableClickTargeting.cs
I've also added an `OnlyPlayers` option in this to limit disabling to only players (personally useful in instances where you need to target a friendly NPC e.g O11/DSR).
> Fix DisableClickTargeting tweak

- Tweaks/DisableClickTargeting.cs
There was a small typo in the cleanup commit which let right clicks on nameplates ignore the tweak's setting. (P.S sorry about the messy code in the initial PR)
> Fix right click on nameplate ignoring disable right click setting (Disable Click Targeting)

- Tweaks/LevelingDungeonCommand.cs
Adds a new command to open the highest level leveling dungeon available to the player in the Duty Finder. A quick QoL to avoid having to scroll through the duty list or remember what's best for your level. Intended to be macro'd or QoLBar'd, but direct input is also feasible.
No subcommands / arguments / settings. Uses excel sheet data to list the available instance content in the game, filters by those that are dungeons, where `RequiredClassJobLevel % 10 == 0`, those that are unlocked by the player, and those that have a required level less than the player's current level on their current job, then selects the max level dungeon of that list.
I tinkered with having an option to auto-check-checkbox-for-queueing but couldn't figure it out in <10 minutes so I went to bed.
> [`LevelingDungeonCommand`] New Tweak: Command to open highest level leveling dungeon available to the player

- Tweaks/UiAdjustment/OpenGlamourDresserToCurrentJob.cs
The tweak was writing to the wrong byte (due to the way all addon offsets shifted in 7.1), causing the Glamour Dresser window to vanish.
This is a quick-fix that corrects the offset for now, but it would probably be best to get the field added to ClientStructs so it can be maintained there.
> [`OpenGlamourDresserToCurrentJob`] Fix vanishing window bug

- Utility/ChatHelper.cs
Use functions and types defined in ClientStructs instead of maintaining a version here
Additionally the helper functions were never used independently, so inline them and save a few conversions
At the time of writing this needs a for wait for a ClientStructs fix to make its way into Dalamud for it to compile and work correctly.
This fixes the tweaks that rely on chat commands to function.
> Update and simplify ChatHelper

- Tweaks/Chat/PrintSearchComment.cs
API 11 added new methods for print chat that allow the use of Lumina SeStrings directly, which removes the need for a conversion back to Dalamud SeString in this tweak
> `[Print Search Comment]` Remove unnecessary conversion to Dalamud SeString

- Tweaks/Chat/CaseInsensitiveCommands.cs
- Tweaks/CommandAlias.cs
Someone should probably verify this can be "adopted"... Anyways.
- Uses the same failed command handler logic as Dalamud does. This should always run post-Dalamud.
- Instead of just forcing the first word to lowercase, intelligently look up the command from Lumina.
- This only makes a difference for GM commands, but hey. It's technically more correct!
- It may make sense (possibly?) to cache these resolutions to not run a LINQ query every time. However, this isn't running per-frame so I'm not sure if it's a big deal.
- Add optional resolution for Dalamud commands as well, so people can use `/XLPlugins` and all.
- This will also intelligently search through Dalamud's command registry, meaning plugins that register uppercase commands will be used if found first. (e.g. a plugin registering …
> [`CaseInsensitiveCommands`] Casexile, but a Tweak!

- Tweaks/Chat/ExpGainLevelPercent.cs
This tweak just adds the percentage of your next level to exp gains in chat.
I like being able to quickly calculate how many more times I need to do an activity to level up and this makes that easier at a glance. 👍
> [`ExpGainLevelPercent`] New tweak

- Tweaks/UiAdjustment/HideUnwantedBanner.cs
This change adds the following GATE (Gold Saucer FATE) related banners to the Hide Unwanted Banners tweak:
- GATE Joined
- GATE Complete
- GATE Failed
> Add GATE Banners to Hide Unwanted Banners tweak

- tweakBlacklist.txt
Cf. #930, the crash is pretty random, but should probably blacklist the tweak until you or someone else can have a look at it.
> Blacklist crashing SubmarineDestinationLetters tweak

- Tweaks/HighResScreenshots.cs
I had trouble figuring out how to use this option and found several others who had the same issue. This change is intended to clarify that Current Keybind must match the ReShade keybind, but the game screenshot keybind is actually used to take the final screenshot.
> Clarify documentation for usage of reshade option

- Tweaks/AutoLockHotbar.cs
I use 3x4 Hotbars which leads to the lock being off-screen, making this the only way to unlock my hotbars if I want to change something outside of combat.
If wanted I can change it to default to being off.
> [`AutoLockHotbar`] Add option to unlock when combat ends

- Tweaks/Tooltips/ShowItemID.cs
Uses GetTextNodeById instead of directly accessing the node by index.
If you instead want to keep the old approach, then additional type checking is required or a CTD is caused by trying to read a null StringPtr when the tooltip is modified by other plugins or has nodes added.
> `ShowItemID` Safer node lookup

- Tweaks/UiAdjustment/ShiftTargetCastBarText.cs
Fixes accessing wrong element when custom nodes are inserted into the castbar
> ShiftTargetCastBarText Fix Node Lookup

- Tweaks/UiAdjustment/CastBarAdjustments.cs
- Tweaks/UiAdjustment/MinimapAdjustments.cs
- Tweaks/UiAdjustment/NotificationToastAdjustments.cs
- Tweaks/UiAdjustment/ReducedDeepDungeonInfo.cs
The only tweaks remaining that are still accessing nodes directly are:
BuffListVerticalGrowth
LimitTargetStatusEffects
These I was not comfortable modifying. I will keep them in mind if I consider making any features that could conflict with them.
All others are either debug/uidebug functions, are carefully check the nodeid/type of node returned from direct acces, or are iterating over all nodes anyways.
> More node safety
