Tweaks/Tooltips/DesynthesisSkill.cs

Instead of displaying your desynthesis skill, it'll show the difference between that skill and the item's desynthesis level.
Useful for determining if you should keep an item for desynth, or to Vendor it.

Optionally show difference in desynthesis skill

---

Tweaks/UiAdjustment/LimitTargetStatusEffects.cs

👋 
If you liked the idea, here it is.

New Tweak: Limit Target Status Effects

---

Helper/UiHelper.Overloads.cs
Tweaks/UiAdjustment/ReducedDeepDungeonInfo.cs

Also added 2 overloads to set AtkCollisionNode position.

Add Tweak: Reduced Deep Dungeon Info

---

Tweaks/UiAdjustment/NotificationToastAdjustments.cs

Mainly used for changing the position now that Burnt Toast exists.

Update Toast tweak to use new Dalamud events

---

Tweaks/UiAdjustment/OldNameplatesTweak.cs

Name and description are placeholders.

Add Tweak: Old Nameplates

---

Tweaks/UiAdjustment/NotificationToastAdjustments.cs

Apparently, the duplicate addon isn't useless, shocking!

Fix missing addon in `Notification Toast Adjustments`

---

Tweaks/UiAdjustment/SmartNameplates.cs

Adds a tweak for [this](https://github.com/goatcorp/suggestions/issues/461) but with a few more options.

Add Tweak: Smart Nameplates

---

Tweaks/Tooltips/CopyHotkey.cs

**Background:**
If you prefer to play in Japanese and also prefer Japanese websites for item checks, the GamerEscape website is not that useful.
For the time being, I added one Japanese website as a new hotkey choice.

Added Eriones (JP) to Tooltip Hotkeys

---

Tweaks/UiAdjustment/TimerOnDutyWaiting.cs

Just to avoid catching it when attached + all exceptions on 😃 .

[`Timer on Duty Waiting`] Avoid caught exception

---

Tweaks/UiAdjustment/PartyListStatusTimers.cs

Didn't even know it was a thing, but sure is:

[`Party List Status Timers`] Add hours formatting

---

Tweaks/HideMouseAfterInactivity.cs

Add tweak to hide cursor after inactivity

---

Tweaks/UiAdjustment/SmartNameplates.cs

Will need to be recompiled once Dalamud fixes the enums in order to fix #158

Smart Nameplates: Use Dalamud's enums

---

Tweaks/FixTarget.cs

[`FixTarget`] Ignore invisible objects

---

Tweaks/AutoOpenCommendWindow.cs
Tweaks/AutoOpenLootWindow.cs

I could not test it enough because I got a CTD and queues.
So a draft for now.

fix: Do not show loot window if in cutscene

---

Debugging/DebugManager.cs
SimpleTweaksPlugin.cs

Default Enabled to false in DebugManager (still set it to true in ST constructor when debug).
Remove DEBUG directive when using /tweaks Debug.

Fix debug menu opened state in release build

---

Tweaks/UiAdjustment/ParameterBarAdjustments.cs

About 7 times faster, all those nanoseconds saved!

[`Parameter Bar Adjustments`] Improve performance

---

Tweaks/DisableMountVolumeChange.cs

This tweak prevent mount music from going quiet when not moving.

Add Tweak: Disable Mount Music Volume Change

---

Tweaks/ScreenshotFileName.cs

Lets you change the date format for screenshot file names.

New Tweak: Screenshot File Name

---

Tweaks/UiAdjustment/GearPositions.cs

for Examine window controller navigation
I'm very interested if there was possibly a better way to write this if you have any feedback on it.

[`Adjust Equipment Positions`] Fix "Examine" cursor movement

---

Tweaks/UiAdjustment/CastBarAdjustments.cs

Avoids the blinking (showing for 1 frame) of 'Casting' and countdown text.

[`Cast Bar Adjustments`] Use OnUpdate to avoid blinking

---

Tweaks/Tooltips/TrackFadedRolls.cs

- Remove all signatures from the tweak, we're all ClientStructs!

[Track Faded Orchestrion Rolls] Update Plugin to 6.2

---

Tweaks/UiAdjustment/ControlHintMirroring.cs

Adding the author property that I never added for `Control Hint Mirroring`.

Add author to `Control Hint Mirroring`

---

Tweaks/BaitCommand.cs

please don't kill me this is my first st

New Tweak: Bait Command

---

SimpleTweaksPlugin.cs
SimpleTweaksPluginConfig.cs

Not sure if this is frowned upon or not, but I really like having SimpleTweaks available in the Dev Menu, like when being built locally, for quick access to the debug window.  But I also like getting auto updates and not having to constantly pull/build.

Add an option to put SimpleTweaks in the Dev Menu on release builds.

---

Tweaks/TreasureHuntTargets.cs

My chocobo died because of this, I'm asking for 36 + 348 Gils to pay the medical bills.

[`Treasure Hunt Targets`] Exclude non-enemies

---

Tweaks/UiAdjustment/ExpandedCurrencyDisplay.cs
Tweaks/UiAdjustment/MoreMoney.cs

It **should** be good, might want to toss into experimental for a little bit.

Add Expanded Currency Display Tweak

---

Tweaks/UiAdjustment/ExpandedCurrencyDisplay.cs

Having half of the calculation in one style and not the other was bugging me.
Also included Icon AutoFit fix.

Expanded Currency Display, Minor Style Fix

---

Tweaks/UiAdjustment/LootWindowDuplicateUniqueItemIndicator.cs

I didn't realize that the armory was also considered for the lootability of items, whoops.

Add Armory Items to LWDUII

---

Utility/UiHelper.Nodes.cs

Going to wait until this is merged before I refactor Expanded Currency Display, and improve Duplicate Loot Indicator.
I want to add image nodes to the loot window to display an X icon, and a Padlock icon for unable to obtain, and already unlocked respectively.

Add UiHelper.Node.cs

---

Tweaks/UiAdjustment/LootWindowDuplicateUniqueItemIndicator.cs

Fixes cross image node loading wrong version and becoming a black square
Fixes node positioning, as the image nodes are already relative to their containing node
Adds Minions and Mounts to "unlootable" rather than "already unlocked"
Probably fix null reference exception by skipping `IsItemActionUnlocked` if itempointer is null

`Enhanced Loot Window` Fixes and Improvements

---

Tweaks/UiAdjustment/ImprovedInterruptableCastbars.cs

Now with 90% less ghetto, and proper support for Focus Targets

`Improved Interruptable Castbars` Improvements

---

Tweaks/UiAdjustment/TargetCastbarCountdown.cs
Utility/UiHelper.Nodes.cs

I'm not entirely convinced this is a good idea to have or not.
If you have any doubts, feel free to veto this tweak.
https://user-images.githubusercontent.com/9083275/221092098-03183947-4261-4259-83f4-aace60b0c316.mp4

Add `Target Castbar Countdown` tweak

---

Debugging/AgentDebug.cs
Tweaks/Chat/DisableChatMovement.cs
Tweaks/CommandAlias.cs
Tweaks/DisableClickTargeting.cs
Tweaks/LongVeil.cs
Tweaks/SmartStrafe.cs
Tweaks/Tooltips/Hotkeys/ViewOnEriones.cs
Tweaks/Tooltips/Hotkeys/ViewOnGamerEscape.cs
Tweaks/UiAdjustment/CustomTimeFormat.cs
Tweaks/UiAdjustment/OldNameplatesTweak.cs
Tweaks/UiAdjustment/SmartNameplates.cs
Utility/Common.cs

I did need to add a `nint` overload for Common.Hook, I converted a couple tweaks from IntPtr to nint.

Warning cleanup

---

Tweaks/UiAdjustment/LootWindowDuplicateUniqueItemIndicator.cs

Adds "Lock Window Position" option based on `Lock Window Positions` tweak.
Adds config options to enable or disable marking `Un-obtainable Items` or `Already Unlocked Items`
Added Changelog.

`Enhanced Loot Window` Add Lock and Config

---

Tweaks/UiAdjustment/TargetCastbarCountdown.cs

Hide Counter when remaining cast time is negative

`Target Castbar Countdown` Hide when below 00.00s

---

Tweaks/Chat/EchoPartyFinder.cs

I have PR'd the included struct to ClientStructs, but it hasn't been merged yet.

Add `Echo Party Finder` tweak

---

Tweaks/UiAdjustment/ExpandedCurrencyDisplay.cs

Potentially addresses NRE when updating simple tweaks on title screen

`Expanded Currency Display` Potentially fix NRE

---

Tweaks/Chat/EchoStorySelection.cs

Repeats the selected story dialogue option in the NPCDialogue chat channel

Add `Echo Story Selection` tweak

---

Tweaks/KeyInterrupt.cs

- Fixes a bug that causes config changes to not be saved.

[`Keyboard Gaming Mode`] Fix configs not being saved

---

Tweaks/UiAdjustment/ColoredDutyRoulette.cs

New Tweak `Color Duty Roulette Names`

---

Tweaks/Chat/EchoPartyFinder.cs

This one didn't actually cause any problems, but is still wrong so should be fixed

`Echo Party Finder` Dispose Fix

---

Tweaks/Chat/EchoStorySelection.cs

Didn't actually cause any problems but it is wrong should should be removed =D

`Echo Story selection` Dispose Fix

---

Tweaks/UiAdjustment/FadeUnavailableActions.cs

This one also did not cause any problems but it is wrong so should be removed.

`Fade Unavailable Actions` Dispose Fix

---

Tweaks/UiAdjustment/LootWindowDuplicateUniqueItemIndicator.cs

Also Removed Lock Loot Window feature, users should simply use the Lock Window Position tweak instead.

`Enhanced Loot Window` Dispose Fix

---

Debugging/AddonDebug.cs

a4 is a byte that indicates whether to call close/hide function if needed or not (and there are some other state updates as well if it's set to true)

Update callback logging

---

Tweaks/UiAdjustment/DutyListBackground.cs

Adds additional checking to hopefully prevent certain crashes?
I doubt these changes will help, but they can't hurt.

`Duty List Background` Improve Tweak Stability

---

Tweaks/UiAdjustment/LootWindowDuplicateUniqueItemIndicator.cs

Also added periods to the other changelog notes. #Consistency

[`EnhancedLootWindow`] Fix description

---

Tweaks/UiAdjustment/DutyListBackground.cs
tweakBlacklist.txt

There continue to be reports of crashes with this tweak.
I am out of ideas as to the cause, therefore am opting to remove the tweak entirely.
It's probably redundant to both IDisableTweak, and Blacklist tweak, if you want to keep the code but Blacklist the tweak that's fine with me.

[`DutyListBackground`] Disable and Blacklist Tweak

---

Tweaks/UiAdjustment/HideHotbarLock.cs

[`HideHotbarLock`] Fix small typo in Description

---

Tweaks/UiAdjustment/TargetCastbarCountdown.cs

Also uses the config delegate as it was originally intended.

[`TargetCastbarCountdown`] Add option to disable on primary target.

---

Debugging/ActionBarDebug.cs
Debugging/PerformanceMonitor.cs
Events/AddonPreSetupAttribute.cs
Events/EventController.cs
SimpleTweaksPlugin.csproj
Tweaks/SanctuarySprintReplacer.cs
Tweaks/UiAdjustment/OpenGlamourDresserToCurrentJob.cs

This is PR'd and tested against the API9 Branch

[`OpenGlamourDresserToCurrentJob`] Add New Tweak

---

Tweaks/UiAdjustment/DutyListBackground.cs

Without Padding:
With Padding:

[`DutyListBackground`] Add Padding

---

Tweaks/UiAdjustment/FastSearch.cs
Utility/FuzzyMatcher.cs

Currently only supports recipes in the crafting log, but I plan on adding support for the market board partial search once I reverse engineer that mess, too.

[`FastSearch`] New Tweak

---

tweakBlacklist.txt

Throws constant logspam for cross hotbar users, I don't have time to look into it for a couple days.

Disable FadeUnavailableActions

---

Tweaks/Chat/ChatSoundsEverywhere.cs

New tweak, thanks @sersorrel for the [idea](https://canary.discord.com/channels/581875019861328007/685275026156683280/1170826087048167434)!

[`ChatSoundsEverywhere`] New Tweak

---

Enums/LinkHandlerId.cs
Tweaks/Tooltips/TrackFadedRolls.cs

- List craftable orchestrion rolls if more than one is present.

[`Track Faded Orchestrion Rolls`] Track individual crafts

---

Debugging/UIDebug.cs

Warning: as of right now, this uses a fork of ClientStructs ([PR here](https://github.com/aers/FFXIVClientStructs/pull/644)). A chunk of the changes are for a refactoring of AtkResNode.DrawFlags to a ViewFlags enum.
Looks like so:

[`UiDebug`] Add AtkTimeline explorer

---

Debugging/ActionBarDebug.cs

- Add overall struct inspector for RHM
- Add per-slot struct inspector
- Add macro name lookup
- Add collection name lookup
- Default name from PopUpText

Improve hotbar debugging

---

Debugging/ActionBarDebug.cs

- Properly handle the new unreleased jobs
- Don't hardcode values

fix: Fix saved hotbar display

---

Tweaks/UiAdjustment/LimitTargetStatusEffects.cs

Add focus target filtering and improve config clarity. I also disabled filtering on the local player, JUST IN CASE (on game updates), as it's tinkering with the status manager.

[`Target Status Adjustments`] Focus target + misc

---

Tweaks/UiAdjustment/TargetCastbarCountdown.cs

It will not compile, not on stable yet, merge when updating for net8 + game update next week.

[`Target Castbar Countdown`] Fix special casts

---

Tweaks/UiAdjustment/LimitTargetStatusEffects.cs
Tweaks/UiAdjustment/RecolorOwnStatusTimers.cs

Fix some sigs

---

Tweaks/UseCollectionCommand.cs

[`UseCollectionCommand`] Fix useMcGuffin sig for Dawntrail

---

SimpleTweaksPlugin.csproj
Tweaks/UiAdjustment/AlwaysYes.cs
Tweaks/UiAdjustment/LimitTargetStatusEffects.cs
Tweaks/UiAdjustment/NotificationToastAdjustments.cs
Tweaks/UiAdjustment/ParameterBarAdjustments.cs
Tweaks/UiAdjustment/RecolorOwnStatusTimers.cs
Tweaks/UiAdjustment/ReducedDeepDungeonInfo.cs

Target Status Adjustments, Notification Toast Adjustments, Parameter Bar Adjustments, Recolor Own Status Timers, and Reduced Deep Dungeon Info

Update my tweaks

---

SimpleTweaksPlugin.csproj
Tweaks/NoSellList.cs
Tweaks/TooltipTweaks.cs
Tweaks/Tooltips/AdditionalItemInfo.cs
Tweaks/Tooltips/BlueActionInfo.cs
Tweaks/Tooltips/CraftingActionInfo.cs
Tweaks/Tooltips/DesynthesisSkill.cs
Tweaks/Tooltips/PrecisionDurability.cs
Tweaks/Tooltips/PrecisionSpiritbond.cs
Tweaks/Tooltips/ShowItemID.cs
Tweaks/UiAdjustment/ExtendedDesynthesisWindow.cs
Tweaks/UiAdjustment/TimeUntilGpMax.cs

Updated a few straightforward tooltip tweaks and UI tweaks that I use.
Tested in-game without any issues.

Update some tooltip tweaks, desynth window and time to GP UI tweaks

---

SimpleTweaksPlugin.csproj
Tweaks/SmartStrafe.cs

This PR fixes `SmartStrafe` to work in Dawntrail and fixes a bug with the camera in GPose.
This fixes the following issues:
* #323
And makes the following PRs redundant:
* #732
* #755

[`SmartStrafe`] Update my tweak for 7.0 & fix bug in GPose

---

SimpleTweaksPlugin.csproj
Tweaks/EquipJobCommand.cs

Updates my tweak for dawntrail.
Changes are mostly reformat (used `dotnet format`), but also switched config system and used new clientstructs naming for gearset id.

Update EquipJobCommand for DT

---

SimpleTweaksPlugin.csproj
Tweaks/EmoteLogServerBarEntry.cs

Change to IDtrBarEntry to fix compliation error

[EmoteLogServerBarEntry] Fix tweak compile error

---

SimpleTweaksPlugin.csproj
Tweaks/UiAdjustment/CastingTextVisibility.cs

update for API10
fixed issue with blank background when no cast text (opening coffers, etc.)
fixed issue with split target text disappearing

[Casting Text Visibility] API10 and bugfix

---

SimpleTweaksPlugin.csproj

Alt + F4 Exit Game

---

SimpleTweaksPlugin.csproj
Tweaks/UiAdjustment/TargetCastbarCountdown.cs

Been using without issue via my APIX PR

Target Castbar Countdown

---

SimpleTweaksPlugin.csproj
Tweaks/UiAdjustment/LootWindowDuplicateUniqueItemIndicator.cs
Utility/UiHelper.Nodes.cs

This one was a little tricky, I'm not sure what changed, but I made it properly use AtkListComponents to get the elements.

Enhanced Loot Window

---

SimpleTweaksPlugin.csproj
Tweaks/UiAdjustment/LootWindowSelectNext.cs

**Requires pending CS PR**
**Requires dalamud to merge CS after PR**
https://github.com/aers/FFXIVClientStructs/pull/1044

Loot Window Select Next

---

Debugging/UIDebug.cs

- Added texture & parts list display when printing `AtkClippingMaskNode`
- Added Offset values when printing `AtkNineGridNode`

Update UI Debug for variant image node types

---

SimpleTweaksPlugin.csproj
Tweaks/HideMouseAfterInactivity.cs

Hey, I figured out how to make this tweak with Dawntrail. And it took me less time than it took to get used to doing pull requests again.
I followed the example from patterns I noticed in the other commits for 7.0 updates for tweaks and tried it out for one of my most missed tweaks, and it worked.

[`Hide Mouse After Inactivity`] - 7.0 Update

---

Tweaks/Chat/StickyChat.cs

Thanks to Kaz for discovering what horrendous code square actually uses

Fix StickyChat

---

SimpleTweaksPlugin.csproj

Been using it since day 1 of DawnTrail, It just works :tm:

MSQ Progress Tweak

---

SimpleTweaksPlugin.csproj
Tweaks/UiAdjustment/LootWindowDuplicateUniqueItemIndicator.cs

Also fixes layering issue where the node was being put over the text node

Restore Enhanced Loot Window

---

SimpleTweaksPlugin.csproj
Tweaks/KeyInterrupt.cs

- Remove from the experimental tweaks list
- Add a warning explaining the keylogger aspect

[`KeyInterrupt`] Re-Enable for Dawntrail

---

Tweaks/UiAdjustment/TargetCastbarCountdown.cs

Made Target Castbar Countdown respect Simple Tweaks Formatting Culture setting.

Fix Target Castbar Countdown Culture Setting

---

SimpleTweaksPlugin.csproj
Tweaks/UiAdjustment/ExpandedCurrencyDisplay.cs

Only confirmed that it works so far, will continue testing locally and fix any issues I come across.
Also updated code style to reflect hanging braces

Expanded Currency Display

---

Tweaks/ContentsFinderConfirmClassSwitch.cs

Update Duty Ready Class Switching

---

SimpleTweaksPlugin.csproj
Tweaks/TryOnCorrectItem.cs

I also tried to 'modernize' the tweak when possible, but not 100% sure the config stuff is being handled in the most modern way.
I also switched to using CS for the hook, and added a "Remove" button to the config UI in case someone wants to remove a special case.

Re-enable `TryOnCorrectItem`

---

SimpleTweaksPlugin.csproj
Tweaks/UiAdjustment/ResizeExperienceBar.cs

I also tried to 'modernize' the tweak when possible.

Re-enable `ResizeExperienceBar`

---

SimpleTweaksPlugin.csproj
Tweaks/UiAdjustment/OpenGlamourDresserToCurrentJob.cs

All addons got bigger in 7.0, and that threw this off by exactly that much

Update Open Glamour Dresser to Current Job

---

Tweaks/UiAdjustment/ImprovedCraftingLog.cs

For the pleasure of having the text translated.

Improved Crafting Log : add language support

---

Tweaks/UiAdjustment/ParameterBarAdjustments.cs

- Fix GP/CP configs being switched (whoops)
- Add reset buttons for bar colors
- Add option to cancel out the default Multiply tints that the game applies to each bar
- Remove deprecated color configs
#861 #840

[`ParameterBarAdjustments`] Fix GP/CP Configs + Misc Adjustments

---

Dalamud.Plugin.Bootstrap.targets
SimpleTweaksPlugin.csproj

I just copied whatever was on https://github.com/goatcorp/SamplePlugin so I could do a build on Linux, so I'm not quite sure if it's correct :d

Infer DalamudLibPath depending on platform

---

Enums/LinkHandlerId.cs
Tweaks/Tooltips/TrackOutfits.cs

`[TrackOutfits]` New Tweak

---

TweakSystem/Attributes/EnumTooltipAttribute.cs
TweakSystem/BaseTweak.cs
Tweaks/UiAdjustment/TalkAdjustments.cs
Utility/Extensions.cs

this is (basically) anna's text box styler plugin that was abandoned a couple years ago but redone using modern advances in science (now with 200% less hooks and memory management)

`[TalkAdjustments]` New Tweak

---

Tweaks/UseCollectionCommand.cs

Simplify tweak, remove sig and use new `CanOpenMcGuffin` and `OpenMcGuffin` functions from CS instead.

[`UseCollectionCommand`] Simplify using new CS functions
